### ISSUE TITLE
CBT.DotNetFx modules need version in package id.

### ISSUE THREAD

**Issue by kingerja** [CommonBuildToolset/CBT.Modules#134]
nuget version resolution for package reference will do two things.
1.  You can only have one package ID installed for a given project.  Making it so your module proj can't target multiple codebases.
2.  You when nuget resolves in the <packagereference it resolves to the highest qfe version so it will take 4.5.1 over 4.5.0 making it impossible to target 4.5.0

**Comment by jeffkl** [comment]
We have new packages for this now
