### ISSUE TITLE
Support non-installed MSBuild when calling NuGet.exe

### ISSUE THREAD

**Issue by josemesona** [CommonBuildToolset/CBT.Modules#16]
Will need to have logic in CBT.NuGet to update Nuget.exe.config with MSBuildToolsPath for the MSBuild ToolsVersion.  It can probably just use the same path that it was called with.

It will probably need to back up any existing config and restore it.  This could get messy when we're calling NuGet.exe a bunch of times in a build.  

Also, it would be nice if we only did this when we **know** that MSBuild isn't installed.

**Comment by jeffkl** [comment]
This is resolved now
