### ISSUE TITLE
Only use CBTNuGetPackagesRestored marker when restoring packages.config

### ISSUE THREAD

**Issue by jeffkl** [CommonBuildToolset/CBT.Modules#162]
The marker file is an optimization only intended for packages.config.  For `project.json` we should be comparing the timestamp of `project.lock.json` and for PackageReference we should look at `project.assets.json`.

**Comment by kingerja** [comment]
We don't have an msbuild property defined for the project.assets.json or project.lock.json file yet when we invoke nuget restore.  Accurately predicting where these lock files should be will be tricky.  We could do some guessing but if we are wrong incremental build is broken.

**Comment by jeffkl** [comment]
Closing for now with hope that NuGet solves this for us
