### ISSUE TITLE
When there is a bad path in a csproj the nuget restore fails with bad error message

### ISSUE THREAD

**Issue by paulgmiller** [CommonBuildToolset/CBT.Modules#229]
[:Here inetroot was used instead of enlistment root.](https://msasg.visualstudio.com/defaultcollection/Bing_and_IPG/_git/Aether/commit/767017daffe59e7fb20dbc47ac9f79cdef9d5123) 

WHich gets an error but the error doesn't say which csproj has the issue. 

The project file could not be loaded. Could not find a part of the path 'd:\src\RelInfra\RelInfra.Common.Library\src\Common\RelInfra.Common.csproj'. d:\src\RelInfra\RelInfra.Common.Library\src\Common\RelInfra.Common.csproj:

So it's really hard to figure out it's DataStore.SqlStore.Test.csproj. Especially if you changed several csprojs. 
You can repo this by re-queuing https://b/build/eee2a584-814a-4bfd-887c-bcefb9588d9f?bq=git_Aether_master_retail this build.

**Comment by jeffkl** [comment]
Code is here: https://github.com/CommonBuildToolset/CBT.Modules/blob/master/src/CBT.NuGet/Internal/MSBuildProjectLoader.cs#L187

I'm pretty sure an InvalidProjectException is thrown with the XML element location but we're not treating that type of exception any differently so I'm thinking the info is getting lost.
