### ISSUE TITLE
Allow specifying targets for ProjectFiles

### ISSUE THREAD

**Issue by aelij** [CommonBuildToolset/CBT.Modules#258]
Currently when specifying a `<ProjectFile />` for traversal, only the default targets are built. If we want to add other targets, we need to modify the project file, add conditions, etc.

It would be very useful to be able to specify the targets directly in the traversal definition, e.g.:

```xml
<ProjectFile Targets="Package" />
```

**Comment by dfederm** [comment]
Typically you would just set the default target in the proj file itself.

Eg:
```
<Project ToolsVersion="14.0" DefaultTargets="Package" xmlns="http://schemas.microsoft.com/developer/msbuild/2003" InitialTargets=";ValidateMSBuildFiles">

```

**Comment by aelij** [comment]
Yes, but that's exactly what I'm trying to avoid. Without this option, you'd have to customize the retail experience (VS) and try to come up with all sorts of conditions so it would only build these targets during traversal and not in VS.

Is there a downside to this suggestion? I think it would be pretty simple to implement.

**Comment by dfederm** [comment]
I don't think it does customize the VS experience. VS still uses `/t:Build` to build and so the default targets would not be run. The default targets would only run when calling MSBuild directly from the command-line, which is your scenario effectively.

**Comment by ohadschn** [comment]
Still, editing MSBuild project files directly deviates from the retail experience. If the build admin can provide an external `dirs.proj` that allows developers to be oblivious to the underlying targets at play, that's a win in my book...

**Comment by jeffkl** [comment]
I think this is a good idea.  I have a few questions:

1. If a `dirs.proj` specified a target to build, that same project would build differently when building the project directly, is that okay?
2. The target that you specify would only be used when building the `Build` target of the `dirs.proj`.  So if you did `msbuild dirs.proj /t:Foo`, it would still run the `Foo` target for every project.  But if you did `msbuild dirs.proj` or `msbuild dirs.proj /t:Build`, it would run the custom target.  Is that okay?

**Comment by aelij** [comment]
IMO:

> If a dirs.proj specified a target to build, that same project would build differently when building the project directly, is that okay?

Yes

> it would still run the Foo target for every project

Does traversal even work for targets other than `Build`? From what I can see, I think not:

https://github.com/CommonBuildToolset/CBT.Modules/blob/814e92afa96843afbb2f7e8e886569740388ce3d/src/CBT.Traversal/build/Traversal.targets#L36

**Comment by ohadschn** [comment]
> VS  still uses /t:Build to build and so the default targets would not be run

I can say for certain that this is not always the case. For my `ccproj` (on CBT), Visual Studio happily runs the `Publish` target if specified in the `DefaultTargets`  (`msbuild /t:build` does not).
