### ISSUE TITLE
CBT.DotNetFx-net472 1.0.1 has an extra directory depth in Facades

### ISSUE THREAD

**Issue by johnthcall** [CommonBuildToolset/CBT.Modules#277]
Comparing [CBT.DotNetFx-net471.1.0.2](https://github.com/CommonBuildToolset/CBT.Modules/releases/tag/CBT.DotNetFx-net471.1.0.2) and [CBT.DotNetFx-net472.1.0.1](https://github.com/CommonBuildToolset/CBT.Modules/releases/tag/CBT.DotNetFx-net472.1.0.1) there is an extra directory level to access Facades in 472. In 471 the directory for System.Collections.dll is build\net471\Facades\System.Collections.dll in 472 it is build\net472\Facades\Facades\System.Collections.dll

I have traced the problem down to https://github.com/CommonBuildToolset/CBT.Modules/commit/b7e32a9f09328d5c03fbb6d3cf05e2a0937d5800 When we migrated from .nuproj to .csproj the extra Facades directory was added to all the CBT.DotNetFx output nupkg.

**Comment by jeffkl** [comment]
Closed via #278
