### ISSUE TITLE
CBT\Module folder appears arbitrary

### ISSUE THREAD

**Issue by kingerja** [CommonBuildToolset/CBT.Modules#44]
A file in the cbt\module folder will either be treated as an extension point or not.
Example cbt.nuget.package\cbt\module\After.Microsoft.Common.targets
this will automatically extend the common targets of course but
CBT.NuGet.Package\CBT\Module\build.props is just a normal file.
Also the After.Microsoft.Common.targets is just a normal file if the correct module isn't loaded.
The point is this appears to be solely based off the ability to reason about all the modules and eventually I expect complicated codebases to have hundreds of modules making it damn near impossible to reason about.  Perhaps these files that are intended to extend should be put in a extend folder or something to show their intent.

**Comment by josemesona** [comment]
I agree, there has been some feedback that CBT module packages should have the same layout as normal build packages.  We'll need to rearrange them soon before people start onboarding...

**Comment by jeffkl** [comment]
Look for a build\packageid.props and build\package.targets

Only difference is if there is a `build\module.config` then auto-load the module.

**Comment by kingerja** [comment]
Per discussion we decided to make the following changes for this issue.
All cbt modules require a module.config in the build folder.
the build.props extension is replaced with packageid.props (this now gets imported in build.props for cbt modules.)
non cbt module build packages are left to be handled by cbt.nuget module and cbt.nuget module will not process cbt build modules.
v1 module support is left in place for the time being.
