### ISSUE TITLE
All properties that CBT defines must be uniquely prefixed

### ISSUE THREAD

**Issue by kingerja** [CommonBuildToolset/CBT.Modules#49]
Property name collision are quite frustrating to debug and I think we should account for this by declaring any property name that is unique to CBT should be prefixed with CBT. 

If you agree let me know and I will start scrubbing.

**Comment by josemesona** [comment]
I tried to do this but there was always a property that I didn't think should be unique to CBT.  There are also targets like `Restore` that I kept generic.  But if you see any property that should obviously have the prefix, feel free to rename it.

**Comment by kingerja** [comment]
So the problem with keeping anything generic is that someone else is going to have something generic and then targets/properties/items/task collide causing issues.  Example in my build system we had this EnableTypeScript but then we needed to import and use someone elses targets that use this property and then a third target that had this.  This three way collision resulted in a very messy tangle of trying to get things to be set and the correct things to run.  Had I instead had CBTEnableTypeScript then I wouldn't of had a problem.
I have seen these collisions at all levels and sometimes I get lucky other times I don't.  But I have a question why wouldn't we call the restore target CBTRestore?  Besides it being distasteful why wouldn't we want to simply adopt a convention for everything we define so there is a very clear notion that this is defined as part of CBT.

**Comment by jeffkl** [comment]
For the `Restore` target, I mainly wanted it to be easy to use for an end user.  I sort of thought of it as an ExtensionMethod where I add the functionality now and then when an official `Restore` target is out there than the CBT one would go away.  The `Restore` target is just a place holder and `RestoreNuGetPackages` does the real work.  

I'd be fine with renaming any of the targets in the `RestoreDependsOn` but I'd rather keep `Restore` until an official one is out.  Any target that a user wouldn't call can also be renamed.

For properties, I'm fine with renaming them where ever it makes sense.

**Comment by kingerja** [comment]
pull #50 is one checking for this.

**Comment by kingerja** [comment]
If Restore and RestoreDependsOn are official or will be official aka not part of CBT then they are not defined by us in the spirit of what that means and therefore we wouldn't want to touch or rename them.  Just retire the redefinition of the target when the official ones are out.  Perhaps even condition an import of that target for down level if need be.  But for all argument purposes consider it external.
There may be other things that match this criteria as well.

So the take away is I will go through these in small change sets and we can debate any renames to ensure they are correct.
