### ISSUE TITLE
Provenance for nuget packages must be ensured

### ISSUE THREAD

**Issue by kingerja** [CommonBuildToolset/CBT.Modules#58]
We must have a way for reproducing our builds for a given changeset/timestamp.  The issue is the project.json will automatically select package dependencies to install and depending on the packages on the feed this selection can differ.

Perhaps have a cbt.nuget.provenance  module that adds a process that generates a project.json with a transitive closure of the packages to install.  Perhaps this process uses a checked in project.lock.json which is kept for the purpose of recording what packages where actually installed for a given build.

Provenance of a build is critical for the enterprise as some times due to lawsuits or government mandate a build lab must be able to exactly reproduce a build.

**Comment by jeffkl** [comment]
We need to test if checking in a lock file is enough

**Comment by kingerja** [comment]
This is an ask to the nuget team and will be handled as part of nuget.  Closing as it should not require any CBT work.
