### ISSUE TITLE
need aggregate package story

### ISSUE THREAD

**Issue by kingerja** [CommonBuildToolset/CBT.Modules#60]
Many build systems rely on having a nuget package overlay another nuget package to form the working "package".

Perhaps we should consider providing a use at your own risk cbt module to provide this functionality.

**Comment by jeffkl** [comment]
I wonder if we can get NuGet to build something official?

**Comment by kingerja** [comment]
That would be ideal but until then we should have a module that we can just retire when/if that occurs.

**Comment by kingerja** [comment]
The module is in I have created a separate issue to track the unit test.
