### ISSUE TITLE
support versioned nugetpath_ properties

### ISSUE THREAD

**Issue by kingerja** [CommonBuildToolset/CBT.Modules#61]
Some times a project will need to reference multiple versions of the same nuget package.  By default we currently generate the nugetpath_ property with the assumption there will only be one version of the package.  If we however generated version specific properties and just had the un-versioned be the latest version?/last listed?  we could then only use NugetPath_ properties for package references of any package.

**Comment by jeffkl** [comment]
The main reason I didn't do this was because in project.json you can't reference the same package twice.  I'm not sure what the story is for the new `<PackageReference />`.  But if you want to bring it back for `packages.config` and think people need it, I'm fine with it.

**Comment by kingerja** [comment]
What build systems really need is a way to encapsulate and version their tools/references/binaries/... This is what nuget was good at and why it was adopted by build systems everywhere.  However with them starting to specialize in the managed build references nichee and break this functionality of nuget I expect what will happen is packages.proj scenario will start to arise that uses the packages.config for pulling down packages and that the csproj will just stick with the project.json.  Or we support a project being able to have both a project.json and a packages.config (which we kind of can now by redirecting the globalpackages.)

Anyway I don't believe packages.config support will ever fade away in favor of the project.json.  My guess is it will be if you can or must use project.json then great but if not use packages.config and in more complicated projects use both.

So that being the case I am going to add support for this to the packages.config scenario at the very least.

**Comment by kingerja** [comment]
This also opens the question I need to figure out if it will need to be supported for cbt modules as well or not.  But I will investigate that further.

**Comment by kingerja** [comment]
marking as won't fix as packagereference doesn't support this either and nuget is going away from having multiple versions being pulled down for a given codebase in general.  Users will just have to build up the property themselves and have the globalpackages install it for them.

If there is significant demand we can revisit the issue for the globalpackages scenario.  But right now the nuget story is still very much being understood and adding this feature will just add complexity for an unknown value.
