### ISSUE TITLE
Optimize package restore for multiple projects

### ISSUE THREAD

**Issue by josemesona** [CommonBuildToolset/CBT.Modules#7]
If the same package exists in multiple packages.config, then Visual Studio will only restore it once.  Currently, the NuGet module will call NuGet restore for every packages.config blindly.

We'll need to come up with a smart way to mirror the functionality in Visual Studio because it's a lot faster

**Comment by jeffkl** [comment]
Closed by aade00e6cc897b79f12593572f3c573e94486a61
